export const enum TODOAPP_ACTION_TYPES  {
    SET_TODOAPP_TASKS,
    SET_TODOAPP_FILTER,
}


export const enum INPUT_ACTION_TYPES {
    SET_INPUT_VALUE = 'SET_INPUT_VALUE',
    SET_INPUT_ERROR = 'SET_INPUT_ERROR'
}
